//commands can be activated using VSCode REST Client extension

### 1. get all persons
GET https://sukalov-phonebook-server.fly.dev/api/persons

### 2. delete Wes Anderson
DELETE https://sukalov-phonebook-server.fly.dev/api/persons/5567546

### 3. add Super Mario
POST https://sukalov-phonebook-server.fly.dev/api/persons
Content-Type: application/json

{
    "name": "Super Mario 2",
    "number": "231-00-01"
}

### 4. empty POST to cause error 400
POST  https://sukalov-phonebook-server.fly.dev/api/persons

### 5. getting error 404
GET https://sukalov-phonebook-server.fly.dev/api/persons/foo

### 6. get Dan Abramov 
GET https://sukalov-phonebook-server.fly.dev/api/persons/628376

### 7. getting error 404 2
GET https://sukalov-phonebook-server.fly.dev/api/foo
